### PR TITLE
cosmic-screencopy-v2

### PR DESCRIPTION
**Pull request by Drakulix**
Fixes https://github.com/pop-os/cosmic-comp/issues/338

### CODE REVIEW

**Comment by Drakulix** [comment]
Seems to work in combination with https://github.com/pop-os/xdg-desktop-portal-cosmic/pull/31 now.

We still need to update cosmic-workspaces and cosmic-applet-minimize.

**Comment by ids1024** [comment]
Hm, I'm sure it was working when I tried it earlier, but now (on a different computer, with multiple monitors; though that may not be relevant), I'm seeing `cosmic-screenshot` hang with https://github.com/pop-os/xdg-desktop-portal-cosmic/pull/31.

`WAYLAND_DEBUG` shows `xdg-desktop-portal-cosmic` not getting any response after calling `capture` on `zcosmic_screencopy_frame_v2`, to capture an output.

https://github.com/pop-os/cosmic-workspaces-epoch/pull/21 (which uses workspace capture, not output capture) seems to be working pretty well though.

**Comment by Drakulix** [comment]
> Hm, I'm sure it was working when I tried it earlier, but now (on a different computer, with multiple monitors; though that may not be relevant), I'm seeing `cosmic-screenshot` hang with [pop-os/xdg-desktop-portal-cosmic#31](https://github.com/pop-os/xdg-desktop-portal-cosmic/pull/31).
> 
> `WAYLAND_DEBUG` shows `xdg-desktop-portal-cosmic` not getting any response after calling `capture` on `zcosmic_screencopy_frame_v2`, to capture an output.
> 
> [pop-os/cosmic-workspaces-epoch#21](https://github.com/pop-os/cosmic-workspaces-epoch/pull/21) (which uses workspace capture, not output capture) seems to be working pretty well though.

I'll try to reproduce it, but since you seem to have a setup where this is broken, could you step through the compositor code to see where it goes wrong?

**Review by ids1024 — APPROVED** [review]
Everything seems to be working well now.

**Pull request merged**
