### PR TITLE
Update `smithay`, with xwayland shell changes

### PR DESCRIPTION
**Pull request by ids1024**
I see there's another breaking Smithay change (noticed this in https://github.com/pop-os/cosmic-comp/pull/477).

For some reason Xwayland clients don't seem to show up now...

### CODE REVIEW

**Comment by ids1024** [comment]
Looks like the client does create the surface, xwayland shell surface sets the serial, and attach a buffer.

Maybe something relies on `wl_surface` being `Some` before it is?

**Comment by ids1024** [comment]
Updated for more Smithay changes. The `Cow` stuff is a bit annoying to deal with.

Xwayland still isn't working here.

**Comment by Drakulix** [comment]
`XwmHandler::map_window_notify` isn't called anymore, working on it.

**Comment by Drakulix** [comment]
Should be fixed by https://github.com/Smithay/smithay/pull/1436

**Review by Drakulix — APPROVED** [review]

**Comment by Tipcat-98** [comment]
On `cosmic-comp-4f076e0` I still get cosmic-comp crashes with certain xwayland apps and empty windows on others (only the title bar shows).

With error messages like:
`May 21 21:23:44 tipcat cosmic-comp[6140]: Failed to handle X11 event`

I'm on Nvidia

**Comment by gabriele2000** [comment]
Agreed, Steam doesn't show up anymore.
Running on a laptop, hybrid Intel+Nvidia GPU setup

**Pull request merged**
