### PR TITLE
Add support for profiling using tracy

### PR DESCRIPTION
**Pull request by ids1024**
I'm not sure entirely how to deal with `profiling::finish_frame!` when there are multiple outputs rendering frames, and some more functions could be annotated, but Tracy seems generally useful for profiling with these changes. So they might as well be merged.

### CODE REVIEW

**Comment by ids1024** [comment]
Looks like `profiling` has support for `puffin` as well? So presumably if we want we should be able to support both fairly easily without having explicit `puffin::profile_function!` calls everywhere.

**Comment by Drakulix** [comment]
> Looks like `profiling` has support for `puffin` as well? So presumably if we want we should be able to support both fairly easily without having explicit `puffin::profile_function!` calls everywhere.

Right. It doesn't hurt to also have puffin-egui available inside the compositor I guess. But we definitely don't want special puffin calls, where we could just use profiling.

**Comment by ids1024** [comment]
Seems `profiling` doesn't currently support the latest version of `puffin`: https://github.com/aclysma/profiling/issues/58.

**Comment by ids1024** [comment]
`profiling` has been updated. But to use `puffin` 0.18 (which it now uses), we'd need to use `puffin_egui` 0.24, which also requires `egui` 0.24, which I ran into an issue updating to: https://github.com/Smithay/smithay-egui/pull/16

**Comment by ids1024** [comment]
Rebased on `master`, and added a change I had stashed to work around a panic in `UtcOffset::current_local_offset().expect("No yet multithreaded")`. That one is annoying, still not sure what to do about it...

**Comment by Drakulix** [comment]
> Rebased on `master`, and added a change I had stashed to work around a panic in `UtcOffset::current_local_offset().expect("No yet multithreaded")`. That one is annoying, still not sure what to do about it...

I mean we do have cosmic-screenshot now, so maybe we can drop the code for creating window screenshots now? That is the only thing that needs the local clock for formatting the file name.

**Comment by ids1024** [comment]
Oh, actually that part can be addressed by temporarily using `time::util::local_offset:set_soundness`. A bit verbose but it's correct even from a paranoid perspective, as long as tracy's thread isn't engaging in any `setenv` shenanigans.

I've committed more `profiling` annotations I've found useful, as well as added them to any function using `puffin::profile_function!`. `profiling` won't work with puffin here until various packages are released and updated. But anyway, if we care about puffin this doesn't change anything. If we don't we can remove the puffin code, but that's somewhat independent.

I also `cargo update` the tracy deps so it's on Tracy 0.10.

This should be fine to merge, and would be useful to have in `master`.

**Review by Drakulix — APPROVED** [review]

**Pull request merged**
