### PR TITLE
Update libcosmic/iced

### PR DESCRIPTION
**Pull request by ids1024**
Still has some build issues to fix.

### CODE REVIEW

**Comment by ids1024** [comment]
This now builds and runs, but ends up with panics calling ` layout.children().next().unwrap()` when a window stack is created.

The widget logic there seems right...

**Comment by ids1024** [comment]
Now it panics in `rounded_rectangle` because `draw_background` is called for `Tab` with an infinite width. Presumably `layout.bounds()` should be finite.

**Review by wash2 — APPROVED** [review]

**Review by Drakulix — CHANGES_REQUESTED** [review]
This PR pins cosmic-comp to a cpu core with 100% usage when creating a stack.

**Comment by ids1024** [comment]
Is that when testing a debug or release build?

When I test it, CPU usage seems fairly similar to the previous version in release builds, maybe a bit higher. (And already higher than it should be). While debug builds seem to have pretty high CPU usage and are less responsive.

Not sure what would have changed in iced here.

**Comment by Drakulix** [comment]
> Is that when testing a debug or release build?
> 
> When I test it, CPU usage seems fairly similar to the previous version in release builds, maybe a bit higher. (And already higher than it should be). While debug builds seem to have pretty high CPU usage and are less responsive.


Ah yeah, debug build. Still that was *fine* before and is now quite unusable, you can't even resize a stack any more. I highly suspect something is running for every frame now, causing redraws.

**Comment by ids1024** [comment]
Right. Software rendering without optimization is generally expected to perform poorly (we could configure cargo to optimize specific dependencies in debug builds to help), but it shouldn't really have gotten worse. And if there's no damage it shouldn't even need to do any rendering each frame.

**Comment by ids1024** [comment]
Running `cargo flamegraph` with a dev build shows it's spending an obscene amount of time in tiny-skia `fill_path` and cosmic-text `shape_until_scroll`. Which is perhaps reasonable performance for those functions without any optimization, but they shouldn't be called so much when nothing is actually changing.

flamegraph

**Comment by ids1024** [comment]
Actually, I seem to be seeing this performance issue on debug builds with `master` as well? Not sure this PR has changed this.

It seems damage tracking is broken for the stack `IcedElement`. `force_redraw` is being called every frame, clearing `last_primitives` so the software renderer has to redraw the whole bar even when nothing has changed. (I'm not sure if forcing redraws like that should be necessary with the way iced does damage tracking?)

Looking at a backtrace, `force_redraw` is called by the stack's `set_activate`, called by `CosmicMapped::set_activate`, called by `Shell::update_active`, called by `Common::refresh_focus`. Probably somewhere here it should be making sure nothing actually happens when the focus hasn't changed.

**Comment by ids1024** [comment]
Bisecting, I seem to be seeing poor responsiveness in debug builds for a terminal in a stack starting with https://github.com/pop-os/cosmic-comp/pull/245.

**Comment by Drakulix** [comment]
Pushed a fix for that, can you rebase and see if this PR is good now? https://github.com/pop-os/cosmic-comp/commit/7234a81672f90f81db67e67c119c6a4f8983ee73

**Comment by ids1024** [comment]
Yep, that seems to help.

Using `opt-level = 2`  in dev builds for `tiny-skia`, `rustybuzz`, and `tty-parser` doesn't seem to add much to build time. So I've added a commit with that. This should help avoid excess CPU usage when there actually is damage. Though the this suggests the `iced_tiny_skia` renderer may need some optimization, particularly around text.

I think this branch should be good to merge. Other than dev build performance, I've been using this branch a fair amount in a release build, and haven't noticed any issues.

**Comment by Drakulix** [comment]
> Using `opt-level = 2`  in dev builds for `tiny-skia`, `rustybuzz`, and `tty-parser` doesn't seem to add much to build time. So I've added a commit with that. This should help avoid excess CPU usage when there actually is damage. Though the this suggests the `iced_tiny_skia` renderer may need some optimization, particularly around text.

Oh neat, didn't know you could selectively optimize like that. Nice!

**Review by Drakulix — APPROVED** [review]

**Comment by ids1024** [comment]
Yep. I saw something recently about how you can now even use cranelift to build your crate while having dependencies built and optimized with LLVM. I still need to experiment with that one.

**Pull request merged**
