### PR TITLE
Draft: initial implementation for ext-foreign-toplevel-list-v1

### PR DESCRIPTION
**Pull request by i509VCB**
Pending on https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/187

### CODE REVIEW

**Comment by ids1024** [comment]
The protocol was merged in wayland-protocols, so I suppose `src/wayland/protocols/ext_foreign_toplevel_list.rs` here could be moved into Smithay?

**Comment by i509VCB** [comment]
How you implement this protocol is probably going to be quite compositor dependent. Hence why I am implementing directly in cosmic

**Comment by ids1024** [comment]
We will need this for https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/124.

**Comment by ids1024** [comment]
This was added in https://github.com/pop-os/cosmic-comp/pull/788.

**Pull request closed without merging**
