### PR TITLE
Xwayland de-scaling

### PR DESCRIPTION
**Pull request by Drakulix**
Adds a "X11 windows handle scaling on their own"-option similar to KDE.

Draft until cosmic-session and cosmic-settings PRs are done and the necessary smithay changes are merged.

### CODE REVIEW

**Comment by ids1024** [comment]
With "applications scale themselves", applications that don't do any scaling like `xterm` and `xcalc` appear small on my 1x scale outputs, not only on the 2x scale output.

I assume this is expected, and a limitation of X, so w can't tell applications to use 1x scale or 2x scale depending on what output they're on? (And perhaps it's also desirable if an app has it's own option to change scaling that won't adjust for monitor. Like increasing the font size in xterm.)

**Comment by ids1024** [comment]
Yeah, looking at how XSETTINGS works, I guess it has to work that way. The X server has a single `_XSETTINGS_S0` selection that applies the same settings to all windows. So we can change it at any time, but only for all windows of all clients.

This does presumably also mean that we don't get proper subpixel font rendering on 1x outputs of the mixed DPI system. Since the buffer is downscaled after rendering. And that those windows waste resources rendering at a higher resolution than presently needed. But presumably the KDE implementation has the same limitations.

In theory it would be good if the wording in cosmic-settings to express the implications of downscaling as a tradeoff as well, but that would make the description quite excessively long and technical.

**Comment by ids1024** [comment]
So this looks reasonable and seems to be working as expected.

**Comment by Drakulix** [comment]
> With "applications scale themselves", applications that don't do any scaling like `xterm` and `xcalc` appear small on my 1x scale outputs, not only on the 2x scale output.

This is only if a 2x or more output is also present though, right?

If so: no nothing we can really do, and the factor is global and we have to assume the application respects it for this to be useful.

In the future we could have a second Xwayland instance and some "compatibility mode" settings in the laucher/app-library/dock.

But before doing that we should support lazily starting Xwayland instances.

**Comment by Drakulix** [comment]
> Yeah, looking at how XSETTINGS works, I guess it has to work that way. The X server has a single `_XSETTINGS_S0` selection that applies the same settings to all windows. So we can change it at any time, but only for all windows of all clients.
> 
> 
> 
> This does presumably also mean that we don't get proper subpixel font rendering on 1x outputs of the mixed DPI system. Since the buffer is downscaled after rendering. And that those windows waste resources rendering at a higher resolution than presently needed. But presumably the KDE implementation has the same limitations.

Yes it does, note this was the same with our "HiDPI Daemon" previously and that was also deemed good enough.

It is almost like we need a new windowing system to properly support this. /s

**Pull request merged**
